export const env = {
    TESTING_MODE: process.env.NEXT_PUBLIC_TESTING_MODE ?? 'true',
    //FRONTEND VARIABLES
    NFT_CONTRACT_ADDRESS_TESTNET : process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS_TESTNET ?? '0x93Ba6D4b1C2B4921b41986C20B95cF154CA8B9B7',
    TOKENID_TESTNET : process.env.NEXT_PUBLIC_TOKENID_TESTNET ?? '2',
    NFT_CONTRACT_ADDRESS_MAINNET : process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS_MAINNET ?? '0x93Ba6D4b1C2B4921b41986C20B95cF154CA8B9B7',
    TOKENID_MAINNET : process.env.NEXT_PUBLIC_TOKENID_MAINNET ?? '2',
    FRONTEND_BASE_URL_DEV : process.env.NEXT_PUBLIC_FRONTEND_BASE_URL_DEV ?? 'http://localhost:3000/',
    SERVER_BASE_URL_DEV : process.env.NEXT_PUBLIC_SERVER_BASE_URL_DEV ?? 'http://localhost:8091/',
    FRONTEND_BASE_URL_PROD : process.env.NEXT_PUBLIC_FRONTEND_BASE_URL_PROD ?? 'https://lit-unity-serverless-oconnor.vercel.app/',
    SERVER_BASE_URL_PROD : process.env.NEXT_PUBLIC_SERVER_BASE_URL_PROD ?? '',
   
    LIT_CHAIN_TESTNET : process.env.NEXT_PUBLIC_LIT_CHAIN_TESTNET ?? 'mumbai',
    LIT_CHAIN_MAINNET : process.env.NEXT_PUBLIC_LIT_CHAIN_MAINNET ?? 'mumbai',
    
    //SERVER VARIABLES
    SERVER_PORT:process.env.SERVER_PORT ?? '',
    ENCRYPTED_FILE_LOCATION_BASE_URL_DEV:process.env.NEXT_PUBLIC_ENCRYPTED_FILE_LOCATION_BASE_URL_DEV ?? 'http://localhost:3000/',
    ENCRYPTED_FILE_LOCATION_BASE_URL_PROD:process.env.NEXT_PUBLIC_ENCRYPTED_FILE_LOCATION_BASE_URL_PROD ?? 'null',
   
    DECRYPT_SYMMETRIC_KEY:process.env.NEXT_PUBLIC_DECRYPT_SYMMETRIC_KEY ?? 'null',
    UNITY_APP_NAME : process.env.NEXT_PUBLIC_UNITY_APP_NAME ?? 'tetrisdemoone',
    UNITY_BUILD_PATH : process.env.NEXT_PUBLIC_UNITY_BUILD_PATH ?? '/unitybuild/test/',
  };